name: Build

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install -U pip ipywidgets anywidget
          python -m pip install -U pylama pytest-asyncio setuptools codecov \
            jupyterlab jupyter_packaging
      - name: Test the extension
        run: |
          make test
          make lint
          make install-local
